### PR TITLE
replace int with big.Int on balance/value fields to avoid overflow

### PR DESCRIPTION
**Pull request by passos**

### CODE REVIEW

**Comment by matthieu** [comment]
This is going to break backward compatibility for anyone using gobcy.

**Comment by passos** [comment]
Compatibility is not a problem If it doesn't work. Using data type `int` for balance of BTC/ETH Address is a mistake. If user has backward compatibility problem for this PR that means they have potential bugs in their program and they need to fix it. 

The following address only has 81 eths. The original implementation won't work in this case.

```
bc := gobcy.API{"test-key", "eth", "main"}
balance, _ := bc.GetAddrBal("37d483bce300dfef828e5c5ba0a045c3e9bdacc4", nil)
result, _ := json.Marshal(balance)
```

```
json: cannot unmarshal number 87943500000000000000 into Go struct field Addr.total_received of type int
```

**Comment by tonnymontana** [comment]
> 1EktcTR22bh3y12tGAYdfEZnYioDdQezUZ

**Comment by quentinlesceller** [comment]
I took the liberty to do a bit of cleanup before merging this. Thank you @passos !

**Pull request merged**
